// src/components/SyntaxHighlightedContainer.jsx
import React, { Component } from 'react'
import prismjs from 'prismjs'
import 'prismjs/components/prism-json'
import 'prismjs/themes/prism-coy.css'

// This wrapper component imports prismjs and highlights the required items
// we use it as a wrapper to avoid unnecessary reinitializations of prismjs
// when using multiple Example items
class SyntaxHightedContainer extends Component {
  componentDidMount() {
    prismjs.highlightAll()
  }
  render() {
    return (
      <div className="language-json syntax-highlighted-container">
        {this.props.children}
      </div>
    )
  }
}

export default SyntaxHightedContainer

// components/SyntaxHighlightedContainer.vue
<template>
  <div class="language-json syntax-highlighted-container">
    <slot></slot>
  </div>
</template>

<script>
import prismjs from 'prismjs'
import 'prismjs/components/prism-json'
import 'prismjs/themes/prism-coy.css'

export default {
  mounted() {
    prismjs.highlightAll()
  }
}
</script>

<style></style>
